sudo: required

language: php

notifications:
  email: false

php:
  - '7.1'

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - env: WP_VERSION=nightly

services:
  - mysql

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - imagemagick
      - libjpeg-dev
      - libpng12-dev
      - nginx
      - realpath

env:
  global:
    - WP_URL="http://localhost:8080"
    - WP_DOMAIN="localhost:8080"
    - DB_NAME="wp"
    - TEST_DB_NAME="tests"
    - WP_TABLE_PREFIX="wp_"
    - WP_ADMIN_USERNAME="admin"
    - WP_ADMIN_PASSWORD="admin"
  matrix:
    - WP_VERSION=latest
    - WP_VERSION=nightly

before_install:
  # create the databases that will be used in the tests
  - mysql -e "create database IF NOT EXISTS $DB_NAME;" -uroot
  - mysql -e "create database IF NOT EXISTS $TEST_DB_NAME;" -uroot
  # set up folders
  - mkdir -p $TRAVIS_BUILD_DIR/www
  - mkdir tools
  # install wp-cli in the `tools` folder
  - wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -P $(pwd)/tools/
  - chmod +x tools/wp-cli.phar && mv tools/wp-cli.phar tools/wp
  # append the `tools` folder to the PATH
  - export PATH=$PATH:$(pwd)/tools
  # prepend the `vendor/bin` folder the PATH
  - export PATH=vendor/bin:$PATH
  # disable XDebug to speed up the tests
  - phpenv config-rm xdebug.ini
  # install imagick PHP extension
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick

install:
  - composer install
  # install WordPress
  - cd $TRAVIS_BUILD_DIR/www
  - wp core download --version=$WP_VERSION
  - wp config create --dbname="$DB_NAME" --dbuser="root" --dbpass="" --dbhost="127.0.0.1" --dbprefix="$WP_TABLE_PREFIX"
  - wp core install --url="$WP_URL" --title="Test" --admin_user="$WP_ADMIN_USERNAME" --admin_password="$WP_ADMIN_PASSWORD" --admin_email="admin@wp.dev" --skip-email
  - wp rewrite structure '/%postname%/' --hard
  # update WordPress database to avoid prompts
  - wp core update-db
  # link the plugin code in the WordPress installation
  - ln -s  $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/www/wp-content/plugins/gattiny
  - ls -la $TRAVIS_BUILD_DIR/www/wp-content/plugins
  # activate the plugin on the site
  - wp plugin deactivate $(wp plugin list --status=active --field=name)
  - wp plugin activate gattiny
  # export a dump of the just installed database to the _data folder to provide tests with a starting fixture
  - wp db export $TRAVIS_BUILD_DIR/tests/_data/dump.sql
  # get back to the build folder
  - cd $TRAVIS_BUILD_DIR
  # install and start Nginx at localhost:8080
  # credit to https://github.com/tburry/travis-nginx-test
  - travis/install-nginx.sh

before_script:
  # set the correct path to phantomjs bin in the .env file
  - sed -i "s#{{phantomjs}}#$(which phantomjs)#" $TRAVIS_BUILD_DIR/.env
  # set the correct path to WP root folder bin in the .env file
  - sed -i "s#{{wp_root_folder}}#$TRAVIS_BUILD_DIR/www#" $TRAVIS_BUILD_DIR/.env
  # build Codeception modules
  - codecept build

script:
  - codecept run unit
  - codecept run integration
  - codecept run functional
  - codecept run acceptance
  - codecept run js
  # let's check for errors here
  - cat /tmp/error.log
